### ISSUE TITLE
missing example usage

### ISSUE THREAD

**Issue by bgiacoma** [AFD-Illinois/iharm3d#30]
from the README it is not clear to me how to run the torus problem that is automatically generated when compiling. Can you add more information? Can it be run on a single core on a laptop?

**Comment by bprather** [comment]
Hi, thanks for catching this!  The knowledge was floating around e.g. script/submit/checklist.txt and proprietary places, and just never got collated in the README.

I think MR #31 should be enough to get you started -- thanks @vedantdhruv96!

If you're interested in plotting: the scripts in script/analysis are written for 3D simulations mostly, and may need to be modified to plot 2D output. 3D simulations can be plotted with e.g. `python script/analysis/movie.py simplest dumps/`
For 2D simulations, it might be easier to use the newer scripts from [pyHARM](https://github.com/AFD-Illinois/pyHARM) -- with e.g. `python scripts/movie.py log_rho_poloidal /path/to/dumps/`.  The example notebook there has some other ways to play with the data directly.

**Comment by bgiacoma** [comment]
I was able to run the Fishbone-Moncrief torus following the new README instructions. I had to play a bit with the grid setup in build_archive/parameters.h in order to get something small to run, but not too small that the code complained (at the end 128*32*32).
Instead I have problems running the movie.py script since it fails while looking for 'eht_out.p' (since it does not exist in the dumps directory)

**Comment by bprather** [comment]
Hi,

Yeah, the grid sizing errors stems from a few bad experiences putting too few zones inside the event horizon (it should be causally isolated from the boundary, which due to the reconstruction stencil requires a few zones' buffer).

You can generate eht_out.p with 'python script/analysis/eht_analysis.py dumps/' -- that will generate a file named according to the simulation start and end times.  When parallelizing analysis, we merge a bunch of these files using eht_unify.py, but a single file can be safely renamed eht_out.p and used as input for movie.py.

Also added this to the README in #32.

**Comment by vedantdhruv96** [comment]
iharm3d passed JOSS review. Closing this.
